name: db-manual-actions

on: push

jobs:
  database-manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ensure datamodel directory exists
        run: |
          mkdir -p ./datamodel

      - name: Install Podman (if not available)
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Setup test database with Podman
        run: |
          podman run -d --name oracle \
            -p 1521:1521 \
            -e ORACLE_RANDOM_PASSWORD=y \
            -e APP_USER=test \
            -e APP_USER_PASSWORD=test \
            -v ./datamodel:/container-entrypoint-initdb.d \
            gvenzl/oracle-free:slim

          # Wait until Oracle DB is ready
          while [[ $(podman logs oracle 2>&1 | grep -c "DATABASE IS READY TO USE") == 0 ]]; do
            sleep 1
          done

      - uses: gvenzl/setup-oracle-sqlcl@v1

      - name: Run SQLcl query
        run: |
          echo "SELECT country_code, official_name, population \
          FROM countries WHERE name = 'Austria';" \
          | sql test/test@localhost/FREEPDB1
