name: db-actions

on: push

jobs:
  database-via-gha-service:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      oracle:
        image: gvenzl/oracle-free:slim
        env:
          ORACLE_RANDOM_PASSWORD: y
          APP_USER: test
          APP_USER_PASSWORD: test
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - uses: gvenzl/setup-oracle-sqlcl@v1

      - name: Run SQLcl
        run: |
          echo "SELECT 'Hey there, hey UCEVA!';" | sql test/test@localhost/FREEPDB1
